# Dependencies
markdown:     rdiscount
pygments:     false

# Permalinks
permalink:    pretty

# Settings
destination:  ./_gh_pages
exclude:      ["README.md"]
paginate:     8

name:         Bootstrap Expo
description:  Beautiful and inspiring uses of Bootstrap
url:          http://expo.getbootstrap.com

future:       false
