# Dependencies
markdown:     rdiscount
permalink:    pretty
pygments:     true

# Settings
destination:  ./_gh_pages
paginate:     8

name:         Bootstrap Expo
description:  Beautiful and inspiring uses of Bootstrap
url:          http://expo.getbootstrap.com

future: 	  false